---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "configmaps.yaml"
  - "persistentvolume.yaml"
  - "poddisruptionbudget.yaml"
  - "services.yaml"
  - "statefulset.yaml"
