---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../../base/postgres"
namespace: "nextcloud"
patches:
  - target:
      kind: "PersistentVolume"
      name: "postgres"
    patch: |-
      - op: "replace"
        path: "/spec/hostPath/path"
        value: "/pool/services/nextcloud-postgres"
