---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../../base/postgres"
namespace: "nextcloud"
patches:
  - target:
      kind: "PersistentVolume"
      labelSelector: "type=postgres"
    patch: |-
      - op: "replace"
        path: "/metadata/name"
        value: "nextcloud-postgres"
      - op: "replace"
        path: "/spec/hostPath/path"
        value: "/pool/services/nextcloud-postgres"
  - target:
      kind: "PersistentVolumeClaim"
      name: "postgres"
    patch: |-
      - op: "replace"
        path: "/spec/volumeName"
        value: "nextcloud-postgres"
