---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "postgres"
  namespace: "nextcloud"
spec:
  hostPath:
    path: "/pool/services/nextcloud-postgres"
  volumeMode: "Filesystem"
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: "Retain"
  capacity:
    storage: "15Ti"
