---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "unbound"
  namespace: "gluetun"
data:
  include.conf: |
    forward-zone:
      name: "cluster.local"
      forward-addr: 10.43.0.10
      forward-tls-upstream: no
    server:
      do-not-query-localhost: no
      private-domain: "cluster.local"
      domain-insecure: "cluster.local"
