---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "gluetun"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "gluetun"
    namespace: "gluetun"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/gluetun"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "prowlarr-config"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "prowlarr-config"
    namespace: "gluetun"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/prowlarr"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "qbittorrent-config"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "qbittorrent-config"
    namespace: "gluetun"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/qbittorrent"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "qbittorrent-media"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "qbittorrent-media"
    namespace: "gluetun"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/media"
