---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "Gateway"
metadata:
  name: "private"
  namespace: "envoy-gateway-system"
spec:
  gatewayClassName: "envoy-gateway"
  infrastructure:
    parametersRef:
      group: "gateway.envoyproxy.io"
      kind: "EnvoyProxy"
      name: "private"
  listeners:
    - name: "http"
      port: 80
      protocol: "HTTP"
      allowedRoutes:
        namespaces:
          from: "All"
  addresses:
    - type: "IPAddress"
      value: "192.168.1.99"
---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "Gateway"
metadata:
  name: "public"
  namespace: "envoy-gateway-system"
spec:
  gatewayClassName: "envoy-gateway"
  infrastructure:
    parametersRef:
      group: "gateway.envoyproxy.io"
      kind: "EnvoyProxy"
      name: "public"
  listeners:
    - name: "http"
      port: 80
      protocol: "HTTP"
      allowedRoutes:
        namespaces:
          from: "All"
  addresses:
    - type: "IPAddress"
      value: "192.168.1.98"
