---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "GatewayClass"
metadata:
  name: "private-envoy-gateway"
  namespace: "envoy-gateway-system"
spec:
  controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
---
---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "GatewayClass"
metadata:
  name: "public-envoy-gateway"
  namespace: "envoy-gateway-system"
spec:
  controllerName: "gateway.envoyproxy.io/gatewayclass-controller"
