---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "application.yaml"
  - "certificate.yaml"
  - "envoyproxy.yaml"
  - "gateway.yaml"
  - "gatewayclass.yaml"
  - "namespace.yaml"
