---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../../base/postgres"
namespace: "freshrss"
patches:
  - target:
      kind: "PersistentVolume"
    patch: |-
      - op: "add"
        path: "/metadata/name"
        value: "freshrss-postgres"
      - op: "replace"
        path: "/spec/hostPath/path"
        value: "/pool/volumes/freshrss-postgres"
