---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "radarr"
  namespace: "radarr"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "radarr"
  ports:
    - port: 7878
      targetPort: 7878
      protocol: "TCP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "radarr-lb"
  namespace: "radarr"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.59"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app.kubernetes.io/name: "radarr"
  ports:
    - port: 80
      targetPort: 7878
      protocol: "TCP"
