---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres"
  namespace: "nextcloud"
  labels:
    cnpg.io/reload: "true"
type: "kubernetes.io/basic-auth"
stringData:
  username: "nextcloud"
  password: "nextcloud"
