---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "postgres" # PATCH
  labels:
    type: "postgres"
spec:
  hostPath:
    path: "" # PATCH
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "local-path"
  capacity:
    storage: "15Ti"
