---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgres"
spec:
  volumeName: "postgres" # PATCH
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  resources:
    requests:
      storage: "1Gi"

