---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgres"
spec:
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  volumeName: "postgres"
  resources:
    requests:
      storage: "1Gi"

