---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "calibre-web-config"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "calibre-web-config"
    namespace: "calibre"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/calibre-web"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "calibre-web-library"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "calibre-web-library"
    namespace: "calibre"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/library"
