---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "calibre-web-config"
  namespace: "calibre"
  annotations:
    volumeType: "hostPath"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "calibre-web-config"
  volumeMode: "Filesystem"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "calibre-web-library"
  namespace: "calibre"
  annotations:
    volumeType: "hostPath"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "calibre-web-library"
  volumeMode: "Filesystem"
