---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "selfsigned-issuer"
spec:
  selfSigned: {}
---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "ca-issuer"
spec:
  ca:
    secretName: "selfsigned-ca"
