---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "plex-tmp"
  namespace: "plex"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "plex-tmp"
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "plex-config"
  namespace: "plex"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "plex-config"
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "plex-media"
  namespace: "plex"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "plex-media"
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
