---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "plex"
  namespace: "plex"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "plex"
  ports:
    - port: 32400
      targetPort: 32400
      protocol: "TCP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "plex-lb"
  namespace: "plex"
  labels:
    ip-pool: "static"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.53"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app.kubernetes.io/name: "plex"
  ports:
    - port: 80
      targetPort: 32400
      protocol: "TCP"
