---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgres"
  namespace: "immich"
  labels:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "database"
spec:
  volumeName: "immich-postgres"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  resources:
    requests:
      storage: "1Gi"
