---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres"
  namespace: "immich"
  labels:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "database"
type: "Opaque"
stringData:
  database: "immich"
  username: "immich"
  password: "immich"
