---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "immich-config"
  namespace: "immich"
  labels:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "server"
data:
  immich.json: |-
    {
      "logging": {
        "enabled": true,
        "level": "log"
      },
      "passwordLogin": {
        "enabled": true
      },
      "server": {
        "externalDomain": "",
        "publicUsers": false
      }
    }
