---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "immich"
  labels:
    app.kubernetes.io/name: "immich"
spec:
  hostPath:
    path: "/pool/services/immich"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: "Retain"
  capacity:
    storage: "15Ti"
  claimRef:
    name: "immich"
    namespace: "immich"
    kind: "PersistentVolumeClaim"
