---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "immich"
  namespace: "immich"
  labels:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "server"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "server"
  ports:
    - port: 2283
      protocol: "TCP"
      targetPort: 2283
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "immich-lb"
  namespace: "immich"
  labels:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "server"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app.kubernetes.io/name: "immich"
    app.kubernetes.io/component: "server"
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 2283
