---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "postgres"
spec:
  hostPath:
    path: "/pool/services/postgres"
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "local-path"
  capacity:
    storage: "15Ti"
  claimRef:
    kind: "PersistentVolumeClaim"
    name: "postgres"
    namespace: "postgres-system"
