---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres"
  namespace: "postgres-system"
type: "Opaque"
stringData:
  host: "postgres.postgres-system.svc.cluster.local:5432"
  database: "postgres"
  username: "postgres"
  password: "postgres"
