---
apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
metadata:
  name: "cluster-gitops"
  namespace: "argocd"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: "create-only"
  generators:
    - git:
        repoURL: "https://github.com/skarre-r/homelab.git"
        revision: "HEAD"
        directories:
          - path: "manifests/cluster/*"
    - git:
        repoURL: "https://github.com/skarre-r/homelab.git"
        revision: "HEAD"
        directories:
          - path: "manifests/apps/*"
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: "argocd"
    spec:
      destination:
        name: "in-cluster"
      project: "default"
      source:
        repoURL: "https://github.com/skarre-r/homelab.git"
        path: "{{path}}"
        targetRevision: "HEAD"
      syncPolicy:
        automated:
          enabled: false
        syncOptions:
          - "RespectIgnoreDifferences=true"
      ignoreDifferences:
        - kind: "Secret"
          jsonPointers:
            - "/data"
            - "/stringData"
