---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "cilium"
#  labels:
#    argocd.argoproj.io/managed-by: "argocd"
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "cilium-secrets"
#  labels:
#    argocd.argoproj.io/managed-by: "argocd"
