---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "gateway"
  namespace: "argocd"
spec:
  destination:
    name: "in-cluster"
    namespace: "gateway-system"
  project: "default"
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - "RespectIgnoreDifferences=true"
  ignoreDifferences: []
  source:
    repoURL: "https://github.com/skarre-r/homelab.git"
    path: "manifests/cluster/gateway"
    targetRevision: "HEAD"
