---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "Gateway"
metadata:
  name: "private"
  namespace: "gateway-system"
spec:
  gatewayClassName: "cilium"
  listeners:
    - name: "http"
      port: 80
      protocol: "HTTP"
      allowedRoutes:
        namespaces:
          from: "All"
  addresses:
    - type: "IPAddress"
      value: "192.168.1.99"
---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "Gateway"
metadata:
  name: "public"
  namespace: "gateway-system"
spec:
  gatewayClassName: "cilium"
  listeners:
    - name: "http"
      port: 80
      protocol: "HTTP"
      allowedRoutes:
        namespaces:
          from: "All"
  addresses:
    - type: "IPAddress"
      value: "192.168.1.98"
