---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "application.yaml"
  - "argocd.yaml"
  - "namespace.yaml"
  - "rbac.yaml"
  - "service.yaml"
  - "subscription.yaml"
