---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "argocd-application-controller-admin"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "admin"
subjects:
  - kind: "ServiceAccount"
    name: "argocd-argocd-application-controller"
    namespace: "argocd"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "everything"
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "argocd-applicationset-controller-everything"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "everything"
subjects:
  - kind: "ServiceAccount"
    name: "argocd-applicationset-controller"
    namespace: "argocd"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "argocd-application-controller-everything"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "everything"
subjects:
  - kind: "ServiceAccount"
    name: "argocd-argocd-application-controller"
    namespace: "argocd"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "read-everything"
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "argocd-server-read-everything"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "read-everything"
subjects:
  - kind: "ServiceAccount"
    name: "argocd-argocd-server"
    namespace: "argocd"
