---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "argocd-server-lb"
  namespace: "argocd"
  labels:
    ip-pool: "static"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.50"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    - name: "https"
      port: 443
      protocol: "TCP"
      targetPort: 8080
    - name: "app"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "argocd-server"
