---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "minio"
  namespace: "argocd"
spec:
  destination:
    name: "in-cluster"
    namespace: "minio-system"
  project: "default"
  syncPolicy:
    syncOptions:
      - "RespectIgnoreDifferences=true"
      - "SkipDryRunOnMissingResource=true"
  ignoreDifferences:
    - kind: "Secret"
      jsonPointers:
        - "/data"
        - "/stringData"
  source:
    repoURL: "https://github.com/skarre-r/homelab.git"
    path: "manifests/cluster/minio"
    targetRevision: "HEAD"
