---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "radicale-config"
  namespace: "radicale"
  labels:
    app.kubernetes.io/name: "radicale"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  volumeName: "radicale-config"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "radicale-data"
  namespace: "radicale"
  labels:
    app.kubernetes.io/name: "radicale"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  volumeName: "radicale-data"
  resources:
    requests:
      storage: "1Gi"

