---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "radicale"
  namespace: "radicale"
  labels:
    app.kubernetes.io/name: "radicale"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "radicale"
  ports:
    - port: 5232
      protocol: "TCP"
      targetPort: 5232
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "radicale-lb"
  namespace: "radicale"
  labels:
    app.kubernetes.io/name: "radicale"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app.kubernetes.io/name: "radicale"
  ports:
    - port: 5232
      protocol: "TCP"
      targetPort: 5232

