---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "application.yaml"
  - "configmap.yaml"
  - "deployment.yaml"
  - "namespace.yaml"
  - "persistentvolume.yaml"
  - "persistentvolumeclaim.yaml"
