---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "cloudflared-creds"
  namespace: "cloudflared"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "cloudflared-creds"
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeMode: "Filesystem"
