---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "gateway-api"
  namespace: "argocd"
spec:
  destination:
    name: "in-cluster"
    namespace: "kube-system"
  project: "default"
  source:
    repoURL: "https://github.com/kubernetes-sigs/gateway-api"
    path: "config/crd/experimental"
    kustomize:
      ignoreMissingComponents: true
    targetRevision: "HEAD"
  syncPolicy:
    syncOptions:
      - "ServerSideApply=true"
