---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "overseerr"
  namespace: "overseerr"
  labels:
    app.kubernetes.io/name: "overseerr"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "overseerr"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "overseerr"
    spec:
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: "overseerr-config"
      containers:
        - name: "overseerr"
          image: "lscr.io/linuxserver/overseerr:latest"
          imagePullPolicy: "Always"
          env:
            - name: "TZ"
              value: "Europe/Oslo"
            - name: "PUID"
              value: "1000"
            - name: "PGID"
              value: "1000"
          ports:
            - containerPort: 5055
              protocol: "TCP"
          startupProbe:
            tcpSocket:
              port: 5055
          readinessProbe:
            tcpSocket:
              port: 5055
          livenessProbe:
            tcpSocket:
              port: 5055
          volumeMounts:
            - mountPath: "/config"
              name: "config"
