---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "overseerr-config"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "overseerr-config"
    namespace: "overseerr"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/overseerr"
