---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "application.yaml"
  - "deployment.yaml"
  - "namespace.yaml"
  - "persistentvolumeclaims.yaml"
  - "persistentvolumes.yaml"
  - "service.yaml"
