---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jellyfin-cache"
  namespace: "jellyfin"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "jellyfin-cache"
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jellyfin-config"
  namespace: "jellyfin"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "jellyfin-config"
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jellyfin-media"
  namespace: "jellyfin"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "jellyfin-media"
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
