---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "jellyfin-lb"
  namespace: "jellyfin"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.56"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app.kubernetes.io/name: "jellyfin"
  ports:
    - port: 80
      targetPort: 8096
      protocol: "TCP"
