---
apiVersion: "gateway.envoyproxy.io/v1alpha1"
kind: "ClientTrafficPolicy"
metadata:
  name: "nextcloud"
  namespace: "nextcloud"
spec:
  targetRefs:
    - group: "gateway.networking.k8s.io"
      kind: "Gateway"
      name: "nextcloud-envoy"
