---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"
metadata:
  name: "nextcloud-external"
  namespace: "nextcloud"
spec:
  hostnames:
    - "n7d.skar.io"
  parentRefs:
    - group: "gateway.networking.k8s.io"
      kind: "Gateway"
      name: "nextcloud"
      namespace: "nextcloud"
  rules:
    - backendRefs:
        - group: ""
          kind: "Service"
          name: "nextcloud"
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: "/"
      filters:
        - type: "ResponseHeaderModifier"
          responseHeaderModifier:
            add:
              - name: "Strict-Transport-Security"
                value: "max-age=15552000; includeSubDomains; preload"
