---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "application.yaml"
  - "httproutes.yaml"
  - "namespace.yaml"
  - "postgres.yaml"
  - "persistentvolumeclaim.yaml"
  - "persistentvolumes.yaml"
  - "secret.yaml"
secretGenerator:
  - name: "nextcloud"
    namespace: "nextcloud"
    behavior: "create"
    options:
      disableNameSuffixHash: true
    type: "Opaque"
    literals: []
