---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "postgres"
  - "application.yaml"
  - "clienttrafficpolicy.yaml"
  - "envoyproxy.yaml"
  - "gateway.yaml"
  - "httproute.yaml"
  - "namespace.yaml"
  - "persistentvolume.yaml"
  - "persistentvolumeclaim.yaml"
secretGenerator:
  - name: "nextcloud"
    namespace: "nextcloud"
    behavior: "create"
    options:
      disableNameSuffixHash: true
    type: "Opaque"
    literals: []
