---
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "nextcloud"
  namespace: "nextcloud"
  annotations:
    volumeType: "hostPath"
spec:
  volumeName: "nextcloud"
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeMode: "Filesystem"
