---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rclone-config"
  namespace: "rclone"
spec:
  hostPath:
    path: "/pool/services/rclone"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: "Retain"
  claimRef:
    kind: "PersistentVolumeClaim"
    name: "rclone-config"
    namespace: "rclone"
  capacity:
    storage: "15Ti"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rclone-data"
  namespace: "rclone"
spec:
  hostPath:
    path: "/pool" # TODO?
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: "Retain"
  claimRef:
    kind: "PersistentVolumeClaim"
    name: "rclone-data"
    namespace: "rclone"
  capacity:
    storage: "15Ti"
