---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "rclone-config"
  namespace: "rclone"
spec:
  volumeName: "rclone-config"
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "rclone-data"
  namespace: "rclone"
spec:
  volumeName: "rclone-data"
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "1Gi"
