---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "rclone"
  namespace: "rclone"
  labels:
    app.kubernetes.io/name: "rclone"
spec:
  type: "ClusterIP"
  ports:
    - port: 5572
      protocol: "TCP"
      targetPort: 5572
  selector:
    app.kubernetes.io/name: "rclone"
