---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "freshrss"
  namespace: "freshrss"
  labels:
    app.kubernetes.io/name: "freshrss"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "freshrss"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "freshrss"
    spec:
      volumes:
        - name: "freshrss"
          persistentVolumeClaim:
            claimName: "freshrss"
      containers:
        - name: "freshrss"
          image: "docker.io/freshrss/freshrss:latest"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "TZ"
              value: "Europe/Oslo"
            - name: "FRESHRSS_ENV"
              value: "production"
            - name: "LISTEN"
              value: "0.0.0.0:8080"
            - name: "CRON_MIN"
              value: "1, 31"
            - name: "POSTGRES_DB" # TODO
              value: "freshrss"
            - name: "POSTGRES_USER"
              value: "freshrss"
            - name: "POSTGRES_PASSWORD"
              value: "freshrss"
            - name: "BASE_URL" # TODO
              value: ""
            - name: "ADMIN_EMAIL"
              value: ""
            - name: "ADMIN_PASSWORD"
              value: ""
            - name: "ADMIN_API_PASSWORD"
              value: ""
            - name: "TRUSTED_PROXY"
              value: ""
            - name: "SERVER_DNS"
              value: ""
          envFrom:
            - secretRef:
                name: "freshrss"
          ports:
            - containerPort: 8080
              protocol: "TCP"
          startupProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
          volumeMounts:
            - mountPath: "/var/www/FreshRSS"
              name: "freshrss"
