---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "application.yaml"
  - "deployment.yaml"
  - "namespace.yaml"
  - "postgres.yaml"
  - "persistentvolumeclaim.yaml"
  - "persistentvolumes.yaml"
  - "services.yaml"
secretGenerator:
  - name: "freshrss"
    namespace: "freshrss"
    behavior: "create"
    options:
      disableNameSuffixHash: true
    type: "Opaque"
    literals: []
