---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "freshrss"
  namespace: "freshrss"
  annotations:
    volumeMode: "hostPath"
spec:
  volumeName: "freshrss"
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeMode: "Filesystem"
