---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "freshrss-config"
spec:
  hostPath:
    path: "/pool/services/freshrss"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: "Retain"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "freshrss-config"
    namespace: "freshrss"
  capacity:
    storage: "15Ti"
