---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "freshrss"
  namespace: "freshrss"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "freshrss"
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "freshrss-lb"
  namespace: "freshrss"
spec:
  type: "LoadBalancer"
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app.kubernetes.io/name: "freshrss"
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
